# Generated by Django 3.1.2 on 2020-10-13 12:28

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=10, null=True, verbose_name='Kategori İsim')),
            ],
            options={
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Başlık Bilgisi Burada Girilir.', max_length=200, null=True, verbose_name='Başlık Giriniz')),
                ('text', models.TextField(max_length=1000, null=True, verbose_name='İçerik Giriniz')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Images')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('kategori', models.ManyToManyField(blank=True, null=True, to='deneme.Kategori')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=django.contrib.auth.models.User)),
            ],
            options={
                'verbose_name_plural': 'Gönderiler',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField(max_length=1000, null=True, verbose_name='Yorum Giriniz')),
                ('comment_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deneme.post')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
